
apiVersion: v1
kind: Service
metadata:
  name: portfolio

spec:
  type: NodePort

  selector:
    app: portfolio

  ports:
  - name: app
    port: 8081
    targetPort: 8081
    nodePort: 30081

  - name: actuator
    port: 9090
    targetPort: 9090
    nodePort: 30090